{% set info = load_file_data("iotaa/resources/info.json") %}

package:
  name: iotaa
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  build:
    - pip
  host:
    - python >=3.9
    - setuptools
test:
  requires:
    - docformatter 1.7.*
    - jq 1.7.*
    - mypy 1.14.*
    - pyfakefs 5.7.*
    - pytest 8.3.*
    - pytest-cov 6.0.*
    - pytest-xdist 3.6.*
    - python >=3.9
    - ruff 0.9.*
about:
  home: https://github.com/maddenp/iotaa
  license: APACHE
