{% set info = load_file_data("iotaa/resources/info.json") %}

package:
  name: iotaa
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  build:
    - pip
  host:
    - python
    - setuptools
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about:
  home: https://github.com/maddenp/iotaa
  license: APACHE
